name: GitHub Pages Deployment
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          path: docs
      - name: setup environment variables
        uses: falti/dotenv-action@v1
        with:
          path: docs/.env
          export-variables: true
          keys-case: upper
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          repository: ${{ env.PROJECT_REPO }}
          path: ${{ env.PROJECT_NAME }}
          ref: ${{ env.PROJECT_BRANCH }}
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Install DocFxMarkdownGen
        run: dotnet tool install -g DocFxMarkdownGen
      - name: Install DocFx
        run: dotnet tool install -g docfx
      - name: Generate Documentation
        run: chmod a+x docs/generate.sh; ./docs/generate.sh
      - name: Yarn Install
        working-directory: docs
        run: yarn install --frozen-lockfile
      - name: Yarn Build
        working-directory: docs
        run: yarn build
      # Popular action to deploy to GitHub Pages:
      # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Build output to publish to the `gh-pages` branch:
          publish_dir: ./docs/build
          # The following lines assign commit authorship to the official
          # GH-Actions bot for deploys to `gh-pages` branch:
          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
          # The GH actions bot is used by default if you didn't specify the two fields.
          # You can swap them out with your own user credentials.
          # user_name: github-actions[bot]
          # user_email: 41898282+github-actions[bot]@users.noreply.github.com